name: Feature Request
description: Request a feature for the project.
title: "[Feature]: "
assignees: [gamertike]
labels: [enhancement]

body:
  - type: textarea
    attributes:
      label: Description
      description: A detailed description of the feature.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to implement
      description: How you would like to the feature to be implemented.
    validations:
      required: true
