name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Check for errors
        run: cargo check

      - name: Test
        run: cargo test

      - name: Format
        run: cargo fmt --check

      - name: Lint
        run: cargo clippy
